# Generated by Django 5.1.6 on 2025-10-13 12:08

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_box_apis', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_key',
            field=models.CharField(default='needs_updated', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='category',
            field=models.CharField(default='needs_updated', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='endpoint',
            field=models.CharField(default='needs_updated', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='api',
            name='icon',
            field=models.CharField(default='update', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='price_per_1000_requests',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='response_time',
            field=models.CharField(default='needs_updated', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='deploy_box_apis.api')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='projects.project')),
            ],
        ),
    ]
