# Generated by Django 5.1.6 on 2025-10-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_box_apis', '0002_api_api_key_api_category_api_endpoint_api_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='api',
            name='response_time',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
