# Generated by Django 5.1.6 on 2026-03-16 11:57

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_box_apis', '0003_alter_api_features_alter_api_response_time'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='A label for this API key', max_length=255)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_hint', models.CharField(help_text='Masked key for display, e.g. dbx_Ab3...xY9z', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project')),
            ],
        ),
    ]
