# Generated by Django 6.0.3 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_box_apis', '0004_apikey'),
        ('projects', '0002_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='apiusage',
            constraint=models.UniqueConstraint(fields=('project', 'api'), name='unique_api_usage'),
        ),
    ]
