# Generated by Django 5.1.6 on 2025-04-09 05:34

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
