# Generated by Django 5.1.6 on 2025-07-01 02:48

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        ('stacks', '0002_stack_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_history',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0.0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_usage', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_on', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Billing History',
            },
        ),
        migrations.CreateModel(
            name='usage_information',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('current_usage', models.FloatField(default=0.0)),
                ('monthly_usage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_info', to='organizations.organization')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_info', to='stacks.stack')),
            ],
            options={
                'verbose_name_plural': 'Usage Information',
            },
        ),
    ]
