# Generated by Django 5.1.6 on 2025-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_billing_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_history',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
