# Generated by Django 5.1.6 on 2025-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_billing_history_stripe_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_history',
            name='stripe_invoice_hosted_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
