# Generated by Django 5.1.6 on 2025-11-30 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_pendinginvites_unique_together'),
        ('payments', '0006_account_accountdiscount_billinghistory_charge_and_more'),
        ('stacks', '0009_purchasablestack_features_alter_stack_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('units_used', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('units_used', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit_name', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('billing_cycle', models.CharField(default='monthly', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='account',
        ),
        migrations.RemoveField(
            model_name='priceplan',
            name='account',
        ),
        migrations.AlterUniqueTogether(
            name='usagedailyrollup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usagedailyrollup',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='account',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='account',
        ),
        migrations.AlterUniqueTogether(
            name='accountdiscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accountdiscount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountdiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='billinghistory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='price_component',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='price_plan',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.RemoveField(
            model_name='discountapplication',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountapplication',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='discountapplication',
            name='invoice_line',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='usagedailyrollup',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='pricecomponent',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='pricecomponent',
            name='price_plan',
        ),
        migrations.RemoveField(
            model_name='pricecomponent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricetier',
            name='price_component',
        ),
        migrations.RemoveField(
            model_name='usagedailyrollup',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='related_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_total_nonnegative',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='payments_in_account_8638a2_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_month',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(default='1e6565b7d56e4133', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('organization', 'invoice_month')},
        ),
        migrations.AddField(
            model_name='dailyusage',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='stacks.stack'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.stack'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='AccountDiscount',
        ),
        migrations.DeleteModel(
            name='BillingHistory',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='DiscountApplication',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PricePlan',
        ),
        migrations.DeleteModel(
            name='PriceComponent',
        ),
        migrations.DeleteModel(
            name='PriceTier',
        ),
        migrations.DeleteModel(
            name='UsageDailyRollup',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UsageEvent',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_cents',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal_cents',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_cents',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_cents',
        ),
        migrations.AlterUniqueTogether(
            name='dailyusage',
            unique_together={('stack', 'usage_date')},
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
