# Generated by Django 5.1.6 on 2026-01-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_dailyusage_invoicelineitem_sku_and_more'),
        ('stacks', '0011_metricdefinition_metricusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_unit', 'Per Unit'), ('tiered', 'Tiered')], max_length=50)),
                ('flat_rate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('tiered_pricing_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='stacks.metricdefinition')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyusage',
            name='stack',
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ratecard'),
        ),
        migrations.DeleteModel(
            name='DailyUsage',
        ),
    ]
