# Generated by Django 5.1.6 on 2025-09-06 04:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_expertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MERN', 'MongoDB, Express, React, Node'), ('MEAN', 'MongoDB, Express, Angular, Node'), ('MEVN', 'MongoDB, Express, Vue.js, Node'), ('LAMP', 'Linux, Apache, MySQL, PHP'), ('DJANGO', 'Django, Python, REST Framework')], max_length=10), size=None)),
                ('location', models.CharField(max_length=100)),
                ('github_profile', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
