services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"

volumes:
  mongo-data: