# Generated by Django 5.1.6 on 2025-04-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_availablestack_remove_stacks_purchased_stack_and_more'),
        ('github', '0005_remove_webhookevents_stack_remove_webhookevents_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stacks',
        ),
    ]
