# Generated by Django 5.1.6 on 2025-04-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_stacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='user',
        ),
    ]
