# Generated by Django 5.1.6 on 2025-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_stack_unique_stack_name_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='pending_billed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stack',
            name='usage',
            field=models.FloatField(default=0),
        ),
    ]
