# Generated by Django 5.1.6 on 2025-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_stack_pending_billed_alter_stack_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='pending_billed',
            new_name='cpu_billed',
        ),
        migrations.RenameField(
            model_name='stack',
            old_name='usage',
            new_name='cpu_usage',
        ),
        migrations.AddField(
            model_name='stack',
            name='memory_billed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stack',
            name='memory_usage',
            field=models.FloatField(default=0),
        ),
    ]
