# Generated by Django 5.1.6 on 2026-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_provider',
            field=models.CharField(default='local', help_text='Authentication provider: local, workos, google, github', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workos_user_id',
            field=models.CharField(blank=True, help_text='WorkOS user ID for SSO-authenticated users', max_length=256, null=True, unique=True),
        ),
    ]
