# Generated by Django 5.1.6 on 2025-03-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_google_cli_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
