# Generated by Django 5.1.6 on 2025-04-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_organizationmember_project_and_more'),
        ('api', '0014_availablestack_remove_stacks_purchased_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.stack'),
        ),
    ]
