# Generated by Django 5.1.6 on 2025-04-03 02:27

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_project_stacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='id',
            field=core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='id',
            field=core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
