# Generated by Django 5.1.6 on 2025-04-03 02:28

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organization_id_alter_organizationmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
