# Generated by Django 5.1.6 on 2025-07-30 10:07

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTransferInvitation',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(max_length=255)),
                ('to_company', models.CharField(blank=True, max_length=255, null=True)),
                ('keep_developer', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTransferAudit',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('initiated', 'Transfer Initiated'), ('accepted', 'Transfer Accepted'), ('declined', 'Transfer Declined'), ('expired', 'Transfer Expired'), ('billing_transferred', 'Billing Transferred'), ('infrastructure_transferred', 'Infrastructure Transferred')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transfer_invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.projecttransferinvitation')),
            ],
        ),
    ]
