# Generated by Django 5.1.6 on 2025-07-30 10:55

from django.db import migrations


def clean_duplicate_pending_invites(apps, schema_editor):
    """Remove duplicate PendingInvites records, keeping only the first one for each organization/email combination"""
    PendingInvites = apps.get_model('organizations', 'PendingInvites')
    
    # Get all pending invites grouped by organization and email
    from django.db.models import Min
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Find duplicates and keep only the first one (lowest ID)
        cursor.execute("""
            DELETE FROM organizations_pendinginvites 
            WHERE id NOT IN (
                SELECT MIN(id) 
                FROM organizations_pendinginvites 
                GROUP BY organization_id, email
            )
        """)


def reverse_clean_duplicate_pending_invites(apps, schema_editor):
    """No reverse operation needed for data cleanup"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_projecttransferinvitation_projecttransferaudit'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_pending_invites, reverse_clean_duplicate_pending_invites),
    ]
