# Generated by Django 5.1.6 on 2025-07-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_clean_duplicate_pending_invites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendinginvites',
            unique_together={('organization', 'email')},
        ),
    ]
