# Generated by Django 5.1.6 on 2025-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_pendinginvites_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('consumption', 'Consumption')], default='free', max_length=50),
        ),
    ]
