# Generated by Django 5.1.6 on 2026-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(max_length=255),
        ),
    ]
