# Generated by Django 5.1.6 on 2025-04-03 02:20

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_availablestack_remove_stacks_purchased_stack_and_more'),
        ('github', '0004_remove_webhookevents_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevents',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='webhookevents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='webhooks',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='webhooks',
            name='user',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('encrypted_token', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('repository', models.CharField(max_length=255)),
                ('webhook_id', models.IntegerField(unique=True)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
        migrations.DeleteModel(
            name='WebhookEvents',
        ),
        migrations.DeleteModel(
            name='Webhooks',
        ),
    ]
