# Generated by Django 5.1.6 on 2025-04-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_remove_webhookevents_stack_remove_webhookevents_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
