from rest_framework import serializers
from .models import Stack, PurchasableStack, Operation
from stacks.resources.resources_manager import RESOURCE_MANAGER_MAPPING


class StackSerializer(serializers.ModelSerializer):
    """Full serializer used by HMAC-authenticated webhook actions (IaC system).

    Allows writing to *all* fields so the IaC container-app can update status,
    iac_state, error_message, instance_usage, etc.
    """

    class Meta:
        model = Stack
        fields = "__all__"
        read_only_fields = ["id", "created_at", "updated_at"]


class StackUserSerializer(serializers.ModelSerializer):
    """Restricted serializer for user-facing endpoints.

    Only exposes fields that an authenticated user is allowed to read/write.
    System-managed fields (status, iac_state, billing, etc.) are read-only.
    """

    class Meta:
        model = Stack
        fields = "__all__"
        read_only_fields = [
            "id",
            "created_at",
            "updated_at",
            "project",
            "purchased_stack",
            "parent_stack",
            "status",
            "error_message",
            "iac_state",
            "instance_usage",
            "instance_usage_bill_amount",
        ]


class PurchasableStackSerializer(serializers.ModelSerializer):
    class Meta:
        model = PurchasableStack
        fields = "__all__"
        read_only_fields = ["id", "created_at", "updated_at"]


class AddResourceSerializer(serializers.Serializer):
    resource_type = serializers.ChoiceField(
        choices=[(k, k) for k in RESOURCE_MANAGER_MAPPING],
        help_text="The resource type key, e.g. AZURERM_CONTAINER_APP",
    )
    config = serializers.DictField(
        required=False,
        default=dict,
        help_text="Optional resource-specific configuration overrides.",
    )
    auto_deploy = serializers.BooleanField(
        required=False,
        default=False,
        help_text="If true, automatically trigger an IaC update after adding.",
    )


class RemoveResourceSerializer(serializers.Serializer):
    resource_id = serializers.CharField(
        help_text="The prefixed resource ID to remove, e.g. res007_abc123.",
    )
    auto_deploy = serializers.BooleanField(
        required=False,
        default=False,
        help_text="If true, automatically trigger an IaC update after removing.",
    )


class ResourceTypeSerializer(serializers.Serializer):
    resource_type = serializers.CharField()
    display_name = serializers.CharField()
    category = serializers.CharField()


# ---------------------------------------------------------------------------
# Deployment Logs
# ---------------------------------------------------------------------------
class DeploymentLogCreateSerializer(serializers.Serializer):
    operation = serializers.ChoiceField(choices=['APPLY', 'DELETE', 'PAUSE', 'RESUME'])


class DeploymentLogAppendSerializer(serializers.Serializer):
    text = serializers.CharField(allow_blank=False)


class DeploymentLogCompleteSerializer(serializers.Serializer):
    status = serializers.ChoiceField(choices=['COMPLETED', 'FAILED'])


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------
class OperationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Operation
        fields = [
            'id', 'stack', 'operation_type', 'status', 'error_message',
            'started_at', 'completed_at', 'created_at', 'updated_at',
        ]
        read_only_fields = fields


class OperationClaimSerializer(serializers.Serializer):
    attempt_id = serializers.CharField(
        max_length=64,
        help_text="Unique token generated by the worker to prove claim ownership.",
    )
    lease_duration_seconds = serializers.IntegerField(
        default=1800, min_value=60, max_value=7200,
        help_text="How long the worker expects to hold the lease (seconds).",
    )


class OperationCompleteSerializer(serializers.Serializer):
    STATUS_CHOICES = [('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')]

    attempt_id = serializers.CharField(
        max_length=64,
        help_text="Must match the attempt_id used during claim.",
    )
    status = serializers.ChoiceField(choices=STATUS_CHOICES)
    error_message = serializers.CharField(required=False, default='', allow_blank=True)


# ---------------------------------------------------------------------------
# Unified Resource (Phase 1)
# ---------------------------------------------------------------------------

class ResourceDependencySerializer(serializers.Serializer):
    id = serializers.CharField(source="depends_on.id")
    name = serializers.CharField(source="depends_on.name")
    resource_type = serializers.CharField(source="depends_on.resource_type")
    dependency_type = serializers.CharField()


class ResourceNodeSerializer(serializers.Serializer):
    """Flat serializer for a single resource node."""
    id = serializers.CharField()
    name = serializers.CharField()
    resource_type = serializers.CharField()
    prefix = serializers.CharField()
    display_name = serializers.SerializerMethodField()
    category = serializers.SerializerMethodField()
    provider_id = serializers.CharField()
    provider_name = serializers.CharField()
    location = serializers.CharField()
    status = serializers.CharField()
    tags = serializers.JSONField()
    attributes = serializers.JSONField()
    parent_id = serializers.CharField(source="parent.id", default=None, allow_null=True)
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()

    def get_display_name(self, obj):
        from stacks.resources.type_registry import ResourceTypeRegistry
        return ResourceTypeRegistry.get_display_name(obj.resource_type)

    def get_category(self, obj):
        from stacks.resources.type_registry import ResourceTypeRegistry
        return ResourceTypeRegistry.get_category(obj.resource_type)


class ResourceTreeSerializer(serializers.Serializer):
    """Builds a nested tree from a flat list of Resource instances.

    Returns top-level (parentless) resources with nested `children` arrays.
    """

    def to_representation(self, resources):
        from stacks.resources.type_registry import ResourceTypeRegistry

        # Build lookup and dependency map
        by_id = {}
        for r in resources:
            node = {
                "id": r.id,
                "name": r.name,
                "resource_type": r.resource_type,
                "prefix": r.prefix,
                "display_name": ResourceTypeRegistry.get_display_name(r.resource_type),
                "category": ResourceTypeRegistry.get_category(r.resource_type),
                "provider_name": r.provider_name,
                "location": r.location,
                "status": r.status,
                "attributes": r.attributes,
                "children": [],
                "dependencies": [],
            }
            by_id[r.id] = (r, node)

        # Wire up parent-child relationships
        roots = []
        for r, node in by_id.values():
            if r.parent_id and r.parent_id in by_id:
                by_id[r.parent_id][1]["children"].append(node)
            else:
                roots.append(node)

        # Wire up dependencies
        for r, node in by_id.values():
            if hasattr(r, "_prefetched_objects_cache") and "dependencies" in r._prefetched_objects_cache:
                for dep in r.dependencies.all():
                    if dep.depends_on_id in by_id:
                        node["dependencies"].append({
                            "id": dep.depends_on_id,
                            "name": by_id[dep.depends_on_id][1]["name"],
                            "dependency_type": dep.dependency_type,
                        })

        return roots


class StackDashboardSerializer(serializers.Serializer):
    """Serializes a stack with its full resource tree for the dashboard."""
    id = serializers.CharField()
    name = serializers.CharField()
    status = serializers.CharField()
    purchased_stack_name = serializers.SerializerMethodField()
    created_at = serializers.DateTimeField()
    resource_tree = serializers.SerializerMethodField()
    health_summary = serializers.SerializerMethodField()

    def get_purchased_stack_name(self, stack):
        return stack.purchased_stack.name if stack.purchased_stack else None

    def get_resource_tree(self, stack):
        resources = stack.unified_resources.all()
        return ResourceTreeSerializer().to_representation(resources)

    def get_health_summary(self, stack):
        resources = stack.unified_resources.all()
        total = len(resources)
        statuses = [r.status.lower() for r in resources]
        healthy = sum(1 for s in statuses if s in ("active", "running", "succeeded", ""))
        failed = sum(1 for s in statuses if s in ("failed", "error"))
        degraded = total - healthy - failed
        return {
            "total_resources": total,
            "healthy": healthy,
            "degraded": degraded,
            "failed": failed,
        }
