from rest_framework import serializers
from .models import Stack, PurchasableStack, Operation
from stacks.resources.resources_manager import RESOURCE_MANAGER_MAPPING


class StackSerializer(serializers.ModelSerializer):
    class Meta:
        model = Stack
        fields = "__all__"
        read_only_fields = ["id", "created_at", "updated_at"]


class PurchasableStackSerializer(serializers.ModelSerializer):
    class Meta:
        model = PurchasableStack
        fields = "__all__"
        read_only_fields = ["id", "created_at", "updated_at"]


class AddResourceSerializer(serializers.Serializer):
    resource_type = serializers.ChoiceField(
        choices=[(k, k) for k in RESOURCE_MANAGER_MAPPING],
        help_text="The resource type key, e.g. AZURERM_CONTAINER_APP",
    )
    config = serializers.DictField(
        required=False,
        default=dict,
        help_text="Optional resource-specific configuration overrides.",
    )
    auto_deploy = serializers.BooleanField(
        required=False,
        default=False,
        help_text="If true, automatically trigger an IaC update after adding.",
    )


class RemoveResourceSerializer(serializers.Serializer):
    resource_id = serializers.CharField(
        help_text="The prefixed resource ID to remove, e.g. res007_abc123.",
    )
    auto_deploy = serializers.BooleanField(
        required=False,
        default=False,
        help_text="If true, automatically trigger an IaC update after removing.",
    )


class ResourceTypeSerializer(serializers.Serializer):
    resource_type = serializers.CharField()
    display_name = serializers.CharField()
    category = serializers.CharField()


# ---------------------------------------------------------------------------
# Deployment Logs
# ---------------------------------------------------------------------------
class DeploymentLogCreateSerializer(serializers.Serializer):
    operation = serializers.ChoiceField(choices=['APPLY', 'DELETE', 'PAUSE', 'RESUME'])


class DeploymentLogAppendSerializer(serializers.Serializer):
    text = serializers.CharField(allow_blank=False)


class DeploymentLogCompleteSerializer(serializers.Serializer):
    status = serializers.ChoiceField(choices=['COMPLETED', 'FAILED'])


# ---------------------------------------------------------------------------
# Operations
# ---------------------------------------------------------------------------
class OperationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Operation
        fields = [
            'id', 'stack', 'operation_type', 'status', 'error_message',
            'started_at', 'completed_at', 'created_at', 'updated_at',
        ]
        read_only_fields = fields


class OperationClaimSerializer(serializers.Serializer):
    attempt_id = serializers.CharField(
        max_length=64,
        help_text="Unique token generated by the worker to prove claim ownership.",
    )
    lease_duration_seconds = serializers.IntegerField(
        default=1800, min_value=60, max_value=7200,
        help_text="How long the worker expects to hold the lease (seconds).",
    )


class OperationCompleteSerializer(serializers.Serializer):
    STATUS_CHOICES = [('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')]

    attempt_id = serializers.CharField(
        max_length=64,
        help_text="Must match the attempt_id used during claim.",
    )
    status = serializers.ChoiceField(choices=STATUS_CHOICES)
    error_message = serializers.CharField(required=False, default='', allow_blank=True)
