# Generated by Django 5.1.6 on 2025-04-15 14:56

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasableStack',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('variant', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('price_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('root_directory', models.CharField(default='', max_length=100)),
                ('instance_usage', models.FloatField(default=0)),
                ('instance_usage_bill_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('purchased_stack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stacks.purchasablestack')),
            ],
        ),
        migrations.CreateModel(
            name='StackBackend',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('root_directory', models.CharField(default='', max_length=100)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='StackDatabase',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('uri', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_usage', models.IntegerField(default=0)),
                ('pending_billed', models.IntegerField(default=0)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='StackFrontend',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('root_directory', models.CharField(default='', max_length=100)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stack',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_stack_name_per_project'),
        ),
    ]
