# Generated by Django 5.1.6 on 2025-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='status',
            field=models.CharField(default='STARTING', max_length=100),
        ),
    ]
