# Generated by Django 5.1.6 on 2025-07-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_stack_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='stack_information',
            field=models.JSONField(default=dict),
        ),
    ]
