# Generated by Django 5.1.6 on 2025-08-07 12:05

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_stack_stack_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasablestack',
            name='prebuilt_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of prebuilt stacks available for immediate use'),
        ),
        migrations.CreateModel(
            name='PrebuiltStack',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchasable_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.purchasablestack')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
