# Generated by Django 5.1.6 on 2025-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_googlecloudbucket_stackgooglecloudrun_stackmongodb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackgooglecloudrun',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stackgooglecloudrun',
            name='state',
            field=models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('STARTING', 'Starting'), ('STOPPING', 'Stopping'), ('DELETING', 'Deleting'), ('CREATING', 'Creating'), ('UPDATING', 'Updating'), ('ERROR', 'Error')], default='STARTING', max_length=100),
        ),
    ]
