# Generated by Django 5.1.6 on 2025-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_stackgooglecloudrun_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackgooglecloudrun',
            name='build_status_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='stackgooglecloudrun',
            name='state',
            field=models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('STARTING', 'Starting'), ('STOPPING', 'Stopping'), ('DELETING', 'Deleting'), ('UPDATING', 'Updating'), ('ERROR', 'Error')], default='STARTING', max_length=100),
        ),
    ]
