# Generated by Django 5.1.6 on 2025-08-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_purchasablestack_prebuilt_quantity_prebuiltstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebuiltstack',
            name='purchasable_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebuilt_stacks', to='stacks.purchasablestack'),
        ),
    ]
