# Generated by Django 5.1.6 on 2025-08-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_alter_prebuiltstack_purchasable_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackgooglecloudrun',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stackmongodb',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stackpostgresql',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stackredis',
            name='stack',
        ),
        migrations.DeleteModel(
            name='GoogleCloudBucket',
        ),
        migrations.DeleteModel(
            name='StackGoogleCloudRun',
        ),
        migrations.DeleteModel(
            name='StackMongoDB',
        ),
        migrations.DeleteModel(
            name='StackPostgreSQL',
        ),
        migrations.DeleteModel(
            name='StackRedis',
        ),
    ]
