# Generated by Django 5.1.6 on 2025-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_stackgooglecloudrun_build_status_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stack',
            name='unique_stack_name_per_project',
        ),
        migrations.AddField(
            model_name='stack',
            name='iac',
            field=models.JSONField(default=dict),
        ),
    ]
