# Generated by Django 5.1.6 on 2025-10-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0006_remove_stackgooglecloudrun_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='environment_name',
            field=models.CharField(default='Development', max_length=50),
        ),
        migrations.AddField(
            model_name='stack',
            name='environment_type',
            field=models.CharField(default='DEV', max_length=50),
        ),
        migrations.AddField(
            model_name='stack',
            name='iac_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='stack',
            name='parent_stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_stacks', to='stacks.stack'),
        ),
    ]
