# Generated by Django 5.1.6 on 2025-10-29 02:22

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0007_stack_environment_name_stack_environment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackdatabase',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stackfrontend',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='iac',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='stack_information',
        ),
        migrations.AddField(
            model_name='stack',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='StackIACAttribute',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iac_attributes', to='stacks.stack')),
            ],
        ),
        migrations.DeleteModel(
            name='StackBackend',
        ),
        migrations.DeleteModel(
            name='StackDatabase',
        ),
        migrations.DeleteModel(
            name='StackFrontend',
        ),
        migrations.AddConstraint(
            model_name='stackiacattribute',
            constraint=models.UniqueConstraint(fields=('stack', 'attribute_name'), name='unique_stack_attribute'),
        ),
    ]
