# Generated by Django 5.1.6 on 2025-11-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0008_remove_stackdatabase_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasablestack',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='stack',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stack',
            name='root_directory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
