# Generated by Django 5.1.6 on 2025-12-23 18:47

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0009_purchasablestack_features_alter_stack_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzurermContainerAppManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermStorageAccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermStorageContainerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermContainerApp',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='AzurermDnsCnameRecord',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('zone_name', models.CharField(max_length=255)),
                ('ttl', models.IntegerField(default=3600)),
                ('record', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermResourceGroup',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermStorageAccount',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('access_tier', models.CharField(default='Hot', max_length=50)),
                ('account_kind', models.CharField(default='StorageV2', max_length=50)),
                ('account_replication_type', models.CharField(default='LRS', max_length=50)),
                ('account_tier', models.CharField(default='Standard', max_length=50)),
                ('allow_nested_items_to_be_public', models.BooleanField(default=False)),
                ('allowed_copy_scope', models.CharField(blank=True, default='', max_length=255)),
                ('cross_tenant_replication_enabled', models.BooleanField(default=False)),
                ('default_to_oauth_authentication', models.BooleanField(default=False)),
                ('dns_endpoint_type', models.CharField(default='Standard', max_length=50)),
                ('edge_zone', models.CharField(blank=True, default='', max_length=255)),
                ('https_traffic_only_enabled', models.BooleanField(default=True)),
                ('infrastructure_encryption_enabled', models.BooleanField(default=False)),
                ('is_hns_enabled', models.BooleanField(default=False)),
                ('large_file_share_enabled', models.BooleanField(default=True)),
                ('local_user_enabled', models.BooleanField(default=True)),
                ('min_tls_version', models.CharField(default='TLS1_2', max_length=50)),
                ('nfsv3_enabled', models.BooleanField(default=False)),
                ('primary_access_key', models.CharField(blank=True, default='', max_length=255)),
                ('primary_blob_connection_string', models.TextField(blank=True, default='')),
                ('primary_connection_string', models.TextField(blank=True, default='')),
                ('provisioned_billing_model_version', models.CharField(blank=True, default='', max_length=50)),
                ('public_network_access_enabled', models.BooleanField(default=True)),
                ('queue_encryption_key_type', models.CharField(default='Service', max_length=50)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('secondary_access_key', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_blob_connection_string', models.TextField(blank=True, default='')),
                ('secondary_connection_string', models.TextField(blank=True, default='')),
                ('sftp_enabled', models.BooleanField(default=False)),
                ('shared_access_key_enabled', models.BooleanField(default=True)),
                ('table_encryption_key_type', models.CharField(default='Service', max_length=50)),
                ('blob_change_feed_enabled', models.BooleanField(default=False)),
                ('blob_change_feed_retention_in_days', models.IntegerField(default=0)),
                ('blob_default_service_version', models.CharField(blank=True, default='', max_length=50)),
                ('blob_last_access_time_enabled', models.BooleanField(default=False)),
                ('blob_versioning_enabled', models.BooleanField(default=False)),
                ('blob_container_delete_retention_days', models.IntegerField(default=7)),
                ('blob_delete_retention_days', models.IntegerField(default=7)),
                ('blob_delete_retention_permanent_delete_enabled', models.BooleanField(default=False)),
                ('share_retention_policy_days', models.IntegerField(default=7)),
                ('static_website_index_document', models.CharField(blank=True, default='', max_length=255)),
                ('static_website_error_404_document', models.CharField(blank=True, default='', max_length=255)),
                ('custom_domain_name', models.CharField(blank=True, default='', max_length=255)),
                ('custom_domain_use_subdomain', models.BooleanField(default=False)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='AzurermStorageContainer',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('storage_account_id', models.CharField(max_length=255)),
                ('container_access_type', models.CharField(choices=[('private', 'Private'), ('blob', 'Blob'), ('container', 'Container')], default='private', max_length=50)),
                ('default_encryption_scope', models.CharField(blank=True, default='', max_length=255)),
                ('encryption_scope_override_enabled', models.BooleanField(default=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='DeployBoxStaticWebsiteItem',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('azurerm_dns_cname_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stacks.azurermdnscnamerecord')),
                ('azurerm_resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.azurermresourcegroup')),
                ('azurerm_storage_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.azurermstorageaccount')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
    ]
