# Generated by Django 5.1.6 on 2026-01-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0010_azurermcontainerapp_azurermcontainerappenvironment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicable_resources', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('unit_name', models.CharField(max_length=50)),
                ('record_frequency_cron', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'unit_name')},
            },
        ),
        migrations.CreateModel(
            name='MetricUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
                ('amount_used', models.DecimalField(decimal_places=6, max_digits=18)),
                ('usage_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='stacks.metricdefinition')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_usage_records', to='stacks.stack')),
            ],
            options={
                'unique_together': {('metric_definition', 'stack', 'resource', 'usage_datetime')},
            },
        ),
    ]
