# Generated by Django 5.1.6 on 2026-02-04 22:25

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0011_metricdefinition_metricusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployBoxrmEdge',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('subdomain', models.CharField(max_length=255)),
                ('root_base_url', models.CharField(max_length=255)),
                ('api_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
