# Generated by Django 5.1.6 on 2026-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0012_deployboxrmedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployboxrmedge',
            name='resolved_api_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployboxrmedge',
            name='resolved_root_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
