# Generated by Django 5.1.6 on 2026-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0013_deployboxrmedge_resolved_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='template_template_container_build_context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deployboxrmedge',
            name='resolved_root_base_url',
            field=models.CharField(default='http://localhost:8000/still-configuring/', max_length=255),
        ),
    ]
