# Generated by Django 5.1.6 on 2026-02-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0014_azurermcontainerapp_template_template_container_build_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasablestack',
            name='stack_infrastructure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='deployboxrmedge',
            constraint=models.UniqueConstraint(fields=('subdomain',), name='uniq_deployboxrm_edge_subdomain'),
        ),
    ]
