# Generated by Django 5.1.6 on 2026-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0015_purchasablestack_stack_infrastructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasablestack',
            name='source_code_location',
            field=models.CharField(blank=True, default='', max_length=255),
        )
    ]
