# Generated by Django 5.1.6 on 2026-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0016_purchasablestack_source_code_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployBoxStaticWebsiteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ]
        ),
        migrations.DeleteModel(
            name='DeployBoxStaticWebsiteItem',
        ),
    ]
