# Generated by Django 5.1.6 on 2026-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0016_purchasablestack_source_code_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeployBoxStaticWebsiteItem',
        ),
    ]
