# Generated by Django 5.1.6 on 2026-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0017_delete_deployboxstaticwebsiteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='thenilermdatabase',
            name='connection_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thenilermdatabase',
            name='credential_tenant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
