# Generated by Django 5.1.6 on 2026-02-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0018_thenilermdatabase_connection_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurermcontainerapp',
            old_name='template_template_container_build_context',
            new_name='template_container_build_context',
        ),
    ]
