# Generated by Django 5.1.6 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0019_rename_template_template_container_build_context_azurermcontainerapp_template_container_build_contex'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurermstorageaccountstaticwebsite',
            name='build_env_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deployboxrmedge',
            name='resolved_root_base_url',
            field=models.CharField(default='https://rmm14f87-8000.use.devtunnels.ms/still-configuring/', max_length=255),
        ),
    ]
