# Generated by Django 5.1.6 on 2026-03-06 00:16

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0020_azurermstorageaccountstaticwebsite_build_env_vars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzurermLogAnalyticsWorkspace',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('sku', models.CharField(default='PerGB2018', max_length=50)),
                ('retention_in_days', models.IntegerField(default=30)),
                ('daily_quota_gb', models.FloatField(default=-1)),
                ('internet_ingestion_enabled', models.BooleanField(default=True)),
                ('internet_query_enabled', models.BooleanField(default=True)),
                ('primary_shared_key', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_shared_key', models.CharField(blank=True, default='', max_length=255)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=255)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
