# Generated by Django 5.1.6 on 2026-03-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0021_azurermloganalyticsworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurermcontainerappenvironment',
            name='log_analytics_workspace_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
