# Generated by Django 5.1.6 on 2026-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0022_azurermcontainerappenvironment_log_analytics_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='liveness_probe_failure_count_threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='liveness_probe_interval_seconds',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='liveness_probe_port',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='liveness_probe_timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='liveness_probe_transport',
            field=models.CharField(default='TCP', max_length=10),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_failure_count_threshold',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_interval_seconds',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_port',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_success_count_threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='readiness_probe_transport',
            field=models.CharField(default='TCP', max_length=10),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_failure_count_threshold',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_initial_delay',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_interval_seconds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_port',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_timeout',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='azurermcontainerapp',
            name='startup_probe_transport',
            field=models.CharField(default='TCP', max_length=10),
        ),
    ]
