# Generated by Django 6.0.3 on 2026-03-24 13:17

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0023_azurermcontainerapp_liveness_probe_failure_count_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployboxrmedge',
            name='resolved_root_base_url',
            field=models.CharField(default='http://localhost:8000/still-configuring/', max_length=255),
        ),
        migrations.CreateModel(
            name='AzurermKeyVault',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('sku_name', models.CharField(default='standard', max_length=50)),
                ('soft_delete_retention_days', models.IntegerField(default=7)),
                ('purge_protection_enabled', models.BooleanField(default=False)),
                ('enabled_for_deployment', models.BooleanField(default=False)),
                ('enabled_for_disk_encryption', models.BooleanField(default=False)),
                ('enabled_for_template_deployment', models.BooleanField(default=False)),
                ('enable_rbac_authorization', models.BooleanField(default=True)),
                ('public_network_access_enabled', models.BooleanField(default=True)),
                ('vault_uri', models.CharField(blank=True, default='', max_length=255)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
