# Generated by Django 6.0.3 on 2026-03-24 16:23

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0024_alter_deployboxrmedge_resolved_root_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployBoxrmPostgresDatabase',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('deploybox_database_id', models.CharField(blank=True, default='', max_length=255)),
                ('db_host', models.CharField(default='deploy-box-postgres.postgres.database.azure.com', max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('db_name', models.CharField(blank=True, default='', max_length=255)),
                ('db_user', models.CharField(blank=True, default='', max_length=255)),
                ('db_password', models.CharField(blank=True, default='', max_length=255)),
                ('connection_string', models.TextField(blank=True, default='')),
                ('sslmode', models.CharField(default='require', max_length=32)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('region', models.CharField(default='eastus', max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
