# Generated by Django 6.0.3 on 2026-03-27 17:27

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0025_deployboxrmpostgresdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzurermLinuxVirtualMachine',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('size', models.CharField(default='Standard_B2s', max_length=100)),
                ('admin_username', models.CharField(default='azureuser', max_length=100)),
                ('admin_ssh_key_public_key', models.TextField(blank=True, default='')),
                ('disable_password_authentication', models.BooleanField(default=True)),
                ('network_interface_ids', models.JSONField(blank=True, default=list)),
                ('os_disk_caching', models.CharField(default='ReadWrite', max_length=50)),
                ('os_disk_storage_account_type', models.CharField(default='Standard_LRS', max_length=50)),
                ('source_image_publisher', models.CharField(default='Canonical', max_length=255)),
                ('source_image_offer', models.CharField(default='ubuntu-24_04-lts', max_length=255)),
                ('source_image_sku', models.CharField(default='server', max_length=255)),
                ('source_image_version', models.CharField(default='latest', max_length=255)),
                ('private_ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('public_ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermNetworkInterface',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('ip_configuration_name', models.CharField(default='internal', max_length=255)),
                ('subnet_id', models.CharField(max_length=255)),
                ('private_ip_address_allocation', models.CharField(default='Dynamic', max_length=50)),
                ('public_ip_address_id', models.CharField(blank=True, default='', max_length=255)),
                ('private_ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('mac_address', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermNetworkSecurityGroup',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('security_rules', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermPublicIp',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('allocation_method', models.CharField(default='Static', max_length=50)),
                ('sku', models.CharField(default='Standard', max_length=50)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AzurermVirtualNetwork',
            fields=[
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RESOURCE', 'Resource'), ('DATA', 'Data')], default='RESOURCE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('azurerm_id', models.CharField(max_length=255)),
                ('azurerm_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='eastus', max_length=255)),
                ('resource_group_name', models.CharField(max_length=255)),
                ('address_space', models.JSONField(blank=True, default=list)),
                ('subnets', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
