# Generated by Django 6.0.3 on 2026-04-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0028_add_operation_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deploymentlog',
            new_name='stacks_depl_stack_i_78fc88_idx',
            old_name='stacks_depl_stack_i_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='stacks_oper_stack_i_983c2d_idx',
            old_name='stacks_oper_stack_i_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='stacks_oper_status_598544_idx',
            old_name='stacks_oper_status_idx',
        ),
    ]
