# Generated by Django 6.0.3 on 2026-04-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0030_add_static_website_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='instance_usage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stack',
            name='instance_usage_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stack',
            name='purchased_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stacks.purchasablestack'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='status',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('DRAFT', 'Draft'), ('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], default='STARTING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='purchasablestack',
            constraint=models.UniqueConstraint(fields=('type', 'variant', 'version'), name='unique_purchasable_stack'),
        ),
    ]
