# Generated by Django 6.0.3 on 2026-04-29 17:09

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0031_alter_stack_instance_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', core.fields.ShortUUIDField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=10)),
                ('provider_id', models.CharField(blank=True, default='', max_length=512)),
                ('provider_name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stacks.resource')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_resources', to='stacks.stack')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, default='requires', help_text='e.g. requires, reads_from, writes_to, routes_to', max_length=50)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='stacks.resource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='stacks.resource')),
            ],
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['stack', 'resource_type'], name='idx_resource_stack_type'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['stack', 'prefix'], name='idx_resource_stack_prefix'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['parent'], name='idx_resource_parent'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('stack', 'resource_type', 'index'), name='unique_resource_per_stack_type'),
        ),
        migrations.AddConstraint(
            model_name='resourcedependency',
            constraint=models.UniqueConstraint(fields=('resource', 'depends_on'), name='unique_resource_dependency'),
        ),
    ]
