name: Django Migrations

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  workflow_dispatch:
jobs:
  migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r Website/requirements.txt

      - name: Run migrations
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEPLOY_BOX_GITHUB_TOKEN_KEY: ${{ secrets.DEPLOY_BOX_GITHUB_TOKEN_KEY }}
        run: |
          source venv/bin/activate
          python Website/manage.py makemigrations
          python Website/manage.py migrate

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t us-central1-docker.pkg.dev/deploy-box-prod/deploy-box-repository/website-1 Website/

      - name: Push Docker Image to Google Cloud Container Registry
        run: |
          gcloud auth activate-service-account --key-file=<(echo "${{ secrets.GCP_SA_KEY }}")
          gcloud auth configure-docker
          docker push us-central1-docker.pkg.dev/deploy-box-prod/deploy-box-repository/website-1

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy
