name: Monthly CRON

on:
  schedule:
    - cron: '0 0 28-31 * *'  # Runs at midnight on the 28th, 29th, 30th, or 31st of each month
  workflow_dispatch:

jobs:
  migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Check if today is the last day of the month
        run: |
          current_day=$(date +'%d')
          last_day=$(date +'%d' -d "$(date +'%Y-%m-01') +1 month -1 day")
          if [ "$current_day" -eq "$last_day" ]; then
            echo "Today is the last day of the month. Proceeding with the workflow."
          else
            echo "Today is not the last day of the month. Skipping."
            exit 0  # Exit the workflow if it's not the last day
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r crontainer/requirements.txt

      - name: Run Main
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          source venv/bin/activate 
          python crontainer/monthly.py