name: Daily CRON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight (00:00) UTC every dayh
  workflow_dispatch:

jobs:
  migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r crontainer/requirements.txt

      - name: Run Main
        env:
          client_id: ${{ secrets.client_id }}
          client_secret: ${{ secrets.client_id }}
        run: |
          source venv/bin/activate 
          python crontainer/main.py