name: Daily CRON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight (00:00) UTC every day
  workflow_dispatch:

jobs:
  daily-usage-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Daily Usage Update
        run: |
          curl -X POST "https://${{ github.ref_name == 'main' && 'www' || github.ref_name }}.deploy-box.com/api/v1/payments/get_daily_usage/"