name: Tests (dev → main PR + manual)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Optional test target (e.g. "payments.tests" or "apps/accounts")'
        required: false
        default: ''
      python_version:
        description: 'Python version'
        required: false
        default: '3.11'
      run_migrate:
        description: 'Run migrations before tests'
        required: false
        default: 'true'   # 'true' or 'false'

concurrency:
  group: tests-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    # Run for manual dispatch OR for PRs where base is main and head is dev
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev') }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    env:
      DJANGO_SETTINGS_MODULE: website.settings
      STRIPE_SECRET_KEY: "sk_test_dummy"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version || '3.11' }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('website/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Migrate (SQLite)
        if: ${{ inputs.run_migrate != 'false' }}  # run by default; can disable in manual run
        run: python manage.py migrate --noinput

      - name: Run tests
        run: |
          if [ -n "${{ inputs.test_path }}" ]; then
            python manage.py test --verbosity 2 "${{ inputs.test_path }}"
          else
            python manage.py test --verbosity 2
          fi

