name: Tests (dev → prod PR)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

concurrency:
  group: pr-to-prod-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev' }}
    runs-on: ubuntu-latest

    # all `run:` steps execute from repo/website
    defaults:
      run:
        working-directory: website

    env:
      DJANGO_SETTINGS_MODULE: website.settings
      STRIPE_SECRET_KEY: "sk_test_dummy"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # requirements live in website/, so hash that path
          key: pip-${{ runner.os }}-${{ hashFiles('website/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test --verbosity 2
